export const ADD_DO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QUANTITY = "ADJUST_QUANTITY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const SAVE_ORDER = "SAVE_ORDER";
export const CLEAR_CART = "CLEAR_CART";
